### ISSUE TITLE
[FR] Add support for limiting OptimizedImages field to subfolder(s) within a Volume

### ISSUE THREAD

**Issue by BenParizek** [nystudio107/craft3-imageoptimize#104]
Currently, we can apply OptimizedImages fields to a Volume. That works great. However, this also means that all subfolders of this Volume will trigger the same image transforms. In many cases, it makes sense to group images that have different transform needs into a single volume. For example:

Volume: Article
- Folder: Full Width Images
- Folder: Portrait Images

In this case, we may want to define two OptimizedImages fields on the same Volume. We can do that now but we will generate twice as many optimized images as we need, as each folder really only requires that we transform the images specific to it. 

It would be nice to have the option to limit or apply OptimizedImages settings to specific subfolders.

**Comment by khalwat** [comment]
I do want to do this, but what was always had me balking is that we can't know which Asset Volume a Field is attached to. Chicken & egg situation.

And then the same field can be added to multiple Asset Volumes.

I also can't put it in the actual Field input, because then that'd be a per-Asset setting.

I guess the best I could do is in the Field Settings itself, you can pick from a list of Asset Volumes, and then select which sub-folders it should apply to for that Asset Volume.

If feels a bit icky tho.

**Comment by shornuk** [comment]
Just started using the plugin this past week. Really great, but I found myself wanting some functionality like this.  I can’t think of a better way though and agree that it doesn’t feel quite right picking folders.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.5

<img width="584" alt="Screen Shot 2019-11-13 at 10 54 16 AM" src="https://user-images.githubusercontent.com/7570798/68781779-46771080-0606-11ea-9962-6dfb768e4e14.png">

<img width="450" alt="Screen Shot 2019-11-13 at 10 51 13 AM" src="https://user-images.githubusercontent.com/7570798/68781799-4f67e200-0606-11ea-8f5e-694794b3812f.png">
