### ISSUE TITLE
Large/multiple GIF uploads cause extreme high server load 

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-imageoptimize#132]
Let me start with saying I don't know for sure if this is caused by Craft or this plugin, so forgive me if I am wrong.

When we add and upload some GIF images in an entry and double click on them so add some data in the custom fields we've added (titel, description, etc.), our server becomes almost unresponsive within a few seconds. Small GIF files (< 2MB) are doable, but larger files aren't. 

Also, often we see the message "this is not an image that can be manipulated", but after a while this is gone and the image does seems to be converted (or whatever happens with it).

![screenshot 2019-01-08 at 11 45 09](https://user-images.githubusercontent.com/1286410/50826134-1fdbaf80-133b-11e9-9213-ad479b386193.png)

The modal and CP are freezing, and multiple PHP-CGI processes seem to freeze on the server, which are causing an extreme high load.  Eventually, when I kill all these processes, restart Lighttpd, it becomes responsive again.

Conclusion: it looks like a process it triggered for GIF files that will cause all these issues and I would really like to find out if this is caused by this plugin, or maybe Craft itself.

Note; we also experienced issues with Craft before, because Craft tried to optimise all GIF files after upload. The config parameter **transformGifs**  was ignored. I created an issue for that (https://github.com/craftcms/cms/issues/3110) which seems to be fixed. But this caused the same issues.

We have all required libs running;

![screenshot 2019-01-08 at 11 43 54](https://user-images.githubusercontent.com/1286410/50826200-46014f80-133b-11e9-89e5-37ca0f0aac97.png)

We really would to see a way to SKIP all conversions for GIF files if possible. We don't need it and it causes a lot of (server) stress.

Craft CMS 3.0.36
PHP 7.0.32
Dedicated server running ubuntu with 8 cores and 16GB ram (so enough for handling some conversions)

Thanks in advance!

**Comment by khalwat** [comment]
So this is likely not an ImageOptimize issue, because it just uses Craft Transforms under the hood... which then end up using Imagick or GD or whatever PHP image library you have installed.

The Optimized Images field does have options that let you ignore creating variants for certain types of images:

<img width="472" alt="google chromescreensnapz316" src="https://user-images.githubusercontent.com/7570798/51001374-e010f580-14fd-11e9-9168-531051754ea3.png">

That should do the trick for you! Just make sure on the frontend, you check to see if there are any image variants before trying to use them (because for GIFs there won't be any).
