### ISSUE TITLE
Distorted Images in Google Cloud

### ISSUE THREAD

**Issue by mattrothenberg** [nystudio107/craft3-imageoptimize#140]
Howdy!

An increasing number of my `imageoptimized` assets are being saved distorted in Google Cloud Platform (GCP).

<img width="787" alt="screen shot 2019-02-23 at 11 34 19 am" src="https://user-images.githubusercontent.com/5148596/53289302-686ff080-3762-11e9-8867-7191b6bed79f.png">

Because I'm not seeing any notifications in the Craft Admin UI about a failed optimization/transformation, I'm curious if you had any thoughts as to where this failure might be occurring? Moreover, the content authors on my site aren't getting any feedback (e.g., an error message) that their image upload failed, which makes them confused when they visit the front-end and see the distorted image.

Thanks for the fantastic plugin! My site wouldn't be the same without it ❤️

**Comment by khalwat** [comment]
So that doesn't look like a distorted image to me, it looks more like an image that isn't fully written out for whatever reason.

Can you explain to me a bit more about how you're using Google Cloud? What plugins to facilitate it, etc.?

**Comment by mattrothenberg** [comment]
Curious. I'm using the Craft Google Cloud plugin to store my assets in a
handful of different buckets. Nothing special beyond that.

I did notice, though, that my Max execution timeout had gotten set to 30
seconds. I just bumped it to 90. Would there be a set of logs I could look
at to see if this were the issue?

Thanks!

**Comment by khalwat** [comment]
You could look at your `phperrors.log` or `web.log` to see any timeouts. Upping that time will likely help, and could be the cause of the problem (though 30 seconds is a pretty long time).

Either way, this is unlikely to be a problem with Image Optimize itself, since it just uses Craft transforms to do its thing. I believe that Andris from P&T mentioned that Google Cloud had some edge cases, but I personally have not used it.  I typically use S3 for images, FWIW.

If you find anything linking this to Image Optimize, I'm happy to re-open the issue.
