### ISSUE TITLE
Imagix webp. 403 Forbidden

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft3-imageoptimize#161]
When I try to create images in Webp format using the IMGIX service, I get an error 403 forbidden.
The problem is present when creating images in the control panel and in templates.

You can see gifs:
![webp](https://user-images.githubusercontent.com/496132/63222099-ac8cfc80-c1ab-11e9-8d3e-c1643ee5eb6c.gif)
When creating images in the format of the jpg, there is no problem
![jpg](https://user-images.githubusercontent.com/496132/63222103-b9115500-c1ab-11e9-97c7-afb9289b6856.gif)

Craft v3.2.9
Amason S3 v1.2.5
ImageOptimize v1.6.0

Logs: 
[logs.zip](https://github.com/nystudio107/craft-imageoptimize/files/3512835/logs.zip)

Thank you

**Comment by khalwat** [comment]
Very odd to me that the images appear in the thumbnail display, but do not work when clicked on.

**Comment by khalwat** [comment]
Do you have any additional information you can give me here @umkasanki ? It seems like this might be due to the Imgix setup in some way?

**Comment by umkasanki** [comment]
No, I haven't.
I noticed strange behavior and decided to inform you.

**Comment by Bcdo** [comment]
I have a similar issue, although not using Imagix, it still might have a correlation. 

The webp image will show in the thumbnail, but pressing it gives a 404 page. Checking the folders, I can see the .webp version have not been created, even with a server that should be able to process it. I can not see any error in the log, and as far as I understand the process of making webp is on by default? or if it were to be turned of, it would not show the image on the thumbnail?

**Comment by khalwat** [comment]
@Bcdo I've seen that in cases where webp was installed/turned on after the image transforms had already been created.

Unfortunately, what Craft does is it looks to see if the transform exists on disk, and if so, it doesn't redo it. In this case, the transform will already exist, so it won't redo it, and ImageOptimize won't get a chance to create the `.webp` variant.

What you can do is delete the actual transform directories (which are proceeded with an underscore `_`), then clear the Asset Index caches, and re-save the Asset Volume in question to allow ImageOptimize to recreate all of the images, along with the `.webp` variants.

**Comment by khalwat** [comment]
Has this been resolved @umkasanki ?

**Comment by khalwat** [comment]
Will re-open if necessary but it is likely that the `.webp` variants here simply don't exist.

ImageOptimize hooks into a Craft event that first when a new transform needs to be made; it is then that we make the `.webp` variants.

However the way Craft works is that if the transformed image already exists on disk, then it does not try to re-create it.

So you'd need to delete the transforms directory (they all start with an underscore `_`) clear the Assets Index cache, and then re-save the image volume for it to re-create the `.webp` variants.

**Comment by Bcdo** [comment]
I apoligize for the late reply, I simply forgot to mention that your solution worked for me. Deleting of the folders, as well as clearing the caches, re-save and re-index the assets. Thank you for your help!

**Comment by alexmglover** [comment]
This isn't working for me. In `getWebPUrl`, the query is being replaced (from `pjpg` to `webpp`) but the signature also needs to be regenerated. If I generate the correct signature and put it in the URL, it works correctlty.

**Comment by khalwat** [comment]
@alexmglover I will re-open the issue

**Comment by josefarrugia** [comment]
I am also having this issue too, however, my webp preview thumbs are not appearing. When clicking the image I get a 403 error. I am currently running this on my local environment with Laravel Valet. 

Any thoughts?

<img width="641" alt="Screenshot 2020-08-19 at 14 55 10" src="https://user-images.githubusercontent.com/8568008/90643905-02b3d600-e22c-11ea-9cee-b7846d2e02be.png">

**Comment by khalwat** [comment]
Thanks @josefarrugia @alexmglover -- I will get a test environment up and running for this issue.

**Comment by mos11charlie** [comment]
+1 here, same experience as @josefarrugia (No webp files created and asset preview showing broken webp thumbnails. Clicking on broken webp thumbnail opens a 403 error)

I'm using IMGIX and I tried several things that might help you diagnose users such as myself having this issue while using IMGIX:

- Craft Pro v3.5.7
- ImageOptimize v1.6.17
- I tested using several different types of IMGIX sources ("Web Folder", "S3", "Web Proxy") and with each source type, the webp failed whenever I used secure URLs. (Keep in mind, my secure url token was valid since the JPGs variants were successfully created). As soon as I disabled secure URLs (removing my IMGIX secure url token from the ImageOptimize plugin settings), webp files were successfully created.
- My IMGIX secure url token is stored in an env var IMGIX_SECURITY_TOKEN and referenced in the ImageOptimize plugin settings as $IMGIX_SECURITY_TOKEN (again, I don't see this being the issue since jpgs were successfully created)
- Separately, in a browser, I used IMGIX's dashboard tool for manually created a signed/secure URL using the same path that ImageOptimize was attempting to create a webp variant and the request was successful (webp image returned instead of 403).

The above scenarios lead me to believe that the webp image requests to IMGIX from ImageOptimize have an invalid hash ("s" url parameter) (while the jpg requests are valid). Hopefully this is of some help! For now I'll simply need to disable secure URLs until we're able to track down and patch the issue.

Thanks!

**Comment by khalwat** [comment]
@josefarrugia Assuming you're using local images, and not Imgix, it's probably what has been discussed earlier in this thread.

Version 1.6.18 added the ability to pass in `--force` to force the re-creation of the transformed images (and thus the webp variants) : https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.18

**Comment by khalwat** [comment]
@mos11charlie @alexmglover sorry for not getting to this sooner. It should be a relatively easy fix, I just need to regenerate the signature. I'm shooting for an update tomorrow to fix it.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.19
