### ISSUE TITLE
Sharp transforms not resaving back to s3

### ISSUE THREAD

**Issue by rellafella** [nystudio107/craft3-imageoptimize#193]
I have my asset volume set up as an s3 bucket serving to the frontend via a CloudFront distribution and then am using ImageOptimize to run Sharp transforms with the serverless image transform service on AWS. 

I am managing to get transformed images via the Base64 encoded urls, but ideally would like those images saved back to the s3 bucket in their designated transform folders. 

I am able to get this result if I use Craft's build in image transforms with ImageOptimize but not with Sharp. 

Running: 
Craft 3.4.5 
ImageOptimize 1.6.11

**Comment by khalwat** [comment]
I don't think it's going to work this way with Sharp. The transformed images are essentially a cache; when Craft does the transforms, it caches them on disk.

When Sharp does the transforms, CloudfFront handles caching and serving the images.

**Comment by rellafella** [comment]
That makes sense, I just wasn't sure if that was the intended functionality or whether I misconfigured something.

**Comment by thijskaspers** [comment]
@khalwat We are exploring Sharp / AWS Lambda Serverless Image Handlers to replace Imgix, since the pricing model change of Imgix increased pricing tenfold for us. The issue we have is that while Sharp does work, it creates really "ugly" URL's with a very long hash after the cloudfront domain.

Is that a Sharp issue (functionality), or is our configuration wrong? For SEO we'd like images to retain their original filenames, but when following this tutorial: https://nystudio107.com/blog/setting-up-your-own-image-transform-service we are not getting that.

Example of what transformed img URL's look like:
https://example.cloudfront.net/eyJidWNrZXQiOiJjb3Jwb3JhdGWxzIiwia2V5IjoicGlvbmVlcnMvMjk3LTUwMHg1MDAucG5nIiwiZWRpdHMiOnsicG5nIjp7InF1YWxpdHkwicHJvZ3Jlc3NpdmUiOmZhbHNlfSwicmVzaXplIjp7IndpZHRMDAsImhlaWdodCI6MjIwLCJmaXQiOiJpbnNpZGUifSwic2hhcnBlbiI6dHJ1ZX19

Probably a base64 encoded string.. ideally the transforms should be stored in the S3 bucket like Craft natively does (without ImageOptimize), and then cloudfront could serve them from the bucket?

**Comment by khalwat** [comment]
Unfortunately, that's just how the Sharp service works currently, @thijskaspers
