### ISSUE TITLE
Files upload from frontend entry forms aren't tranformed right away

### ISSUE THREAD

**Issue by janhenckens** [nystudio107/craft3-imageoptimize#237]
### Describe the bug
We have a site where  participants can create an account and then create entries from a frontend entry form. Files uploaded from that form don't get transformed right away and show up in the CP as images that have to upscaled:

![afbeelding](https://user-images.githubusercontent.com/755428/98561816-9a641600-22a9-11eb-89e5-0e99f30294cf.png)

If we then simply save the asset from the CP, the transforms do get generated and everything works without issue.

We're filling the fields using `->setFieldValuesFromRequest('fields')` and Craft handles the upload and creation of the assets.

I tried figuring out where Craft does the asset creation to see if a certain event doesn't get fired but couldn't get to the bottom of it.

Could you have a look? Thanks!

### Versions
- Plugin version: 1.6.19
- Craft version: 3.5.14

**Comment by khalwat** [comment]
So this is how it works by design, it will create a queue job that will resave the asset variants. If you absolutely want them saved immediately, you can run the queue yourself manually ala: https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/console/controllers/OptimizeController.php#L122
