### ISSUE TITLE
Separate Sizes from other Settings

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#24]
It would be nice to separate the image sizes from the other settings. 
We use Content builder a lot and give the user the option to say which ratio the image can be for example a slide use rather landscape and for a grid with a lot images a 1:1 ratio fit better. 

In Imager we do it so:
```
{% set defaults = {
  cn: 'a-image',
  modifiers: [],
  data: {},
  js: null,
  waypoint: null,
  waypointAni: null,
  image: null,
  sizes: [
    { width: 1600 },
    { width: 1000 },
    { width: 500 },
    { width: 250 },
    { width: 125 }
  ],
  mode: 'crop',
  position: null,
  ratio: null
} %}
```

```
{% set images = craft.imager.transformImage(opt.image, opt.sizes, imageSettings) %}
```

In short. Global Image Settings would be nice and overwrites like this:
```
  sizes: [
    { width: 1600, 'aspectRatioX': 16.0, 'aspectRatioY': 10.0, },
    { width: 1000, 'aspectRatioX': 1.0, 'aspectRatioY': 1.0, },
    { width: 500 },
    { width: 250 },
    { width: 125 }
  ],
```

would be a good option.

**Comment by khalwat** [comment]
So the thing you need to keep in mind about ImageOptimize is that one of the advantages is using the Field for your settings, so that you get the images optimized _when the asset is saved_ rather than when a frontend request is happening.

For that reason, I'd recommend against using it the way you were using Imager for templating on the frontend. Instead, I'd create a Field or multiple Fields that have the sizes you want in them, so ImageOptimize can pre-generate the image transforms.

**Comment by davidhellmann** [comment]
Yeah, tried the other way now!
