### ISSUE TITLE
Ability to disable filesize checking

### ISSUE THREAD

**Issue by mattgrayisok** [nystudio107/craft3-imageoptimize#258]
### Is your feature request related to a problem? Please describe.

Currently when a user visits an Asset's Details Page, IO will perform a curl for every image variant in order to obtain the image's filesize. This causes significant page load issues when the image source is an external, dynamically generated image platform (Imgix, Servd), as it causes the Asset Details page load time to be equal to the time taken to generate all of the image variants *serially*.

The offending line is here:

https://github.com/nystudio107/craft-imageoptimize/blob/d163cced55f64976974a3ab73a51bf54a15beb4c/src/templates/_components/fields/OptimizedImages_input.twig#L100

Currently when using Servd or Imgix, and you visit an asset details page before any background pre-generate tasks have finished processing, the pages can take upwards of 1 minute to load. Changing the above template to:

```
 {% set thisFileSize = 0 %}
```

Brings the page load times back to a normal sub 1s range. Even if background pre-generate tasks have completed previously, page load times can be in the 10s range for images with a lot of variants.

There's a larger question here concerning whether Image Optimise should be performing pre-generate tasks for services like Imgix and Servd which will happily generate all of the image transforms *in parallel* on-demand. I have actually forced IO to **not** pre-generate transforms for Servd by not implementing the getTransformUrl() function in the driver.

### Describe the solution you would like

1. Easy option: Allow disabling of filesize fetches on asset details page at either then plugin or driver level
2. Challenging option: Wish you were using an async capable or multi threaded language and allow transform drivers to specify whether they can run in parallel.  Adjust the transform and filesize logic to fork workers to process in parallel accordingly.

### Describe alternatives you have considered

Table flip

**Comment by khalwat** [comment]
So option 1 already exists -- for each OptimizedImages field, there's an option to simply not display the image variants:

<img width="620" alt="Screen Shot 2021-02-12 at 10 18 46 AM" src="https://user-images.githubusercontent.com/7570798/107786345-c87b4b00-6d1b-11eb-80a5-c71de0576add.png">

As far as pre-generating the images goes, it shouldn't be an expensive operation for drivers like Imgix, because all IO is doing is generating the URL itself, and saving that into a model that goes into the db, so it can be accessed without further db requests on the frontend when a page loads.

What part of this process are you seeing slowdowns in? Just the display of the images in the Asset Detail view?

I've been considering a better way to handle displaying the images, because it causes other problems for people too, if they have an improperly configured setup (it uses `curl`). The only reason I use `curl` is that I could:

- Determine whether an image exists without downloading the entire file (it just asks for the header)
- Display something nice rather than just a broken image if the image doesn't exist

Thoughts?

**Comment by mattgrayisok** [comment]
Ah ok, I hadn't noticed the switch you've pointed out. That will probably just solve the issue and that will be my recommendation for clients moving forward.

I guess it might be nice to allow these images to still be shown but without the expensive filesize call but maybe I'm just being greedy :)

I had assumed that background pre-generation jobs for external services like Servd and Imgix would cause IO to actually cURL the url in order to get the image generated and cached on the external platform, hence the `prefetchRemoteFile` function. But having just searched for that in the codebase I can see that all references to it are commented out so perhaps that was the old behaviour but no longer? This bit doesn't really matter for Servd specifically anyway as it's working fine with its current setup - it was just the page load times whilst grabbing the file sizes that was causing issues.

**Comment by khalwat** [comment]
Yeah the prefectRemoteFile was once a thing, but I decided it actually wasn't helpful in these cases.

So the main issue is the displaying of the images in the Asset Detail view, something which I do want to address at some point.
