### ISSUE TITLE
Image sizes display on asset editor broken depending on browser

### ISSUE THREAD

**Issue by myleshyson** [nystudio107/craft3-imageoptimize#301]
### Describe the bug
The ui on the asset editor that shows different variants and file sizes between optimized and non optimized images is broken on firefox and safari, in that it doesnt show the correct file sizes. It's hard to explain so I'll just post some screenshots.

Chrome correctly showing file size differences.

<img width="468" alt="Screen Shot 2021-11-17 at 4 06 18 PM" src="https://user-images.githubusercontent.com/11747187/142282457-c073917b-ef3f-4044-a2d0-f94cfd7614e3.png">

Firefox just showing the same file size between optimized and not optimized.

<img width="468" alt="Screen Shot 2021-11-17 at 4 07 03 PM" src="https://user-images.githubusercontent.com/11747187/142282539-5bcdfa7e-ad8f-46b7-a705-31ff7b4bb925.png">

Safari not showing the file sizes at all.

<img width="468" alt="Screen Shot 2021-11-17 at 4 07 41 PM" src="https://user-images.githubusercontent.com/11747187/142282667-8b6c8607-3dd4-4cf4-a4cb-9557252aa3db.png">

### To reproduce
Upload an asset. Go to the edit page for that asset.

### Expected behaviour
The file sizes between browsers are consistent. 

### Versions
- Plugin version: 1.6.37
- Craft version: 3.7.20

**Comment by khalwat** [comment]
So this is because the method I'm using to check whether the browser supports webp or not apparently works in Chrome, but doesn't work in Safari or FireFox, because they don't have a complete implementation of WebP support (they support displaying webp, but not creating a webp data url from a canvas element).

As a fallback, if WebP can't be displayed, it uses the source images instead (JPEG in this case).

Looks like the methodology here might work better: https://developers.google.com/speed/webp/faq#in_your_own_javascript

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/3024b222996068dd40ce841959f8839d8d1d18da

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.38”,
```
Then do a `composer clear-cache && composer update`
