### ISSUE TITLE
[Craft 4.0]: Field needs saving before it can be edited

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft3-imageoptimize#325]
### Describe the bug
When creating a new Optimized Image field, we cannot select a ratio or add or remove variants.
The field needs to be saved and then edited so that we can make changes.

Looks like it comes from a JS error when selecting the OptimizedImage type:
```
Uncaught TypeError: Craft.OptimizedImagesInput is not a constructor
    at <anonymous>:4:1
    at m (jquery.js?v=1650530108:2:867)
    at Pe (jquery.js?v=1650530108:2:48866)
    at w.fn.init.append (jquery.js?v=1650530108:2:50070)
    at Object.appendBodyHtml (Craft.js:1836:18)
    at fieldsettings.js:79:19
```

### Versions
- Plugin version: latest dev
- Craft version: latest dev (4.x)

**Comment by khalwat** [comment]
FWIW, I'd suggest using the tagged beta versions of both Craft CMS and also of plugins. The reason is they provide landmarks that allow us to attempt to replicate your issue with the exact same setup.

Also the `dev-` branches may have things checked in that aren't fully baked. So for both Craft and ImageOptimize you can use:

```
^4.0.0-beta.1
```

...as your semver.

I will have a look at this, though!

**Comment by MattWilcox** [comment]
+1 on this issue. JS error on field creation that stops any JS dependent controls working. If you save, then edit the field, things work again.

This is the JS error:

<img width="929" alt="Screenshot 2022-04-22 at 09 45 00" src="https://user-images.githubusercontent.com/814039/164676238-488583bd-2dcc-4e7b-8861-5f578c76cee3.png">

**Comment by simonkuran** [comment]
I'm experiencing this issue as well with 4.0.0-beta.3.

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-imageoptimize/issues/344
