### ISSUE TITLE
output the wrong img size

### ISSUE THREAD

**Issue by LieselotV** [nystudio107/craft3-imageoptimize#361]
### Describe the bug
When I look in the inspector. I see that it always uploads the image with the same size as the browser width. But it still recalculates the correct size of the image. (see printscreen)
If I refresh the page after deleting all the images in the network. Suddenly it loads the largest image and this 2x. It looks like it ignores the code.

I used the same code as in another craft project (Craft Solo 3.7.25.1) where it works fine.

My code:
```
      <figure class="relative overflow-hidden pb-3x5 w-full h-0">
        <picture class="h-full w-full object-cover">
            <source srcset="{{ image.optimizedImagesField.srcsetWebP() }}"
                    sizes="auto"
                    type="image/webp" />
            <source srcset="{{ image.optimizedImagesField.srcset() }}"
                    sizes="auto"
                    type="image/jpeg" />
            <img class="lazyload absolute h-full w-full object-cover"
                src="{{ image.optimizedImagesField.placeholderBox() }}"
                srcset="{{ image.optimizedImagesField.srcset() }}"
                data-aspectratio="{{ image.width }}/{{ image.height }}"
                data-sizes="auto"
                alt="{{ image.title }}"
                style="object-position: {{ image.focalPoint|first * 100 }}% {{ image.focalPoint|last * 100 }}%;" />
        </picture>
      </figure>
```

I tried to remove or replace all the sizes artibutes (with "100vw), but it doesn't change anything.

### Expected behaviour
The image is now displayed at 30% of the browser's width. For example the browser is 1000px wide, the image should take the optimized image with a width of 300px (or the nearest ratio).
This works fine at my other craft project (Craft Solo 3.7.25.1) with the same code.

### Screenshots
<img width="413" alt="Schermafbeelding 2022-11-03 om 18 34 05" src="https://user-images.githubusercontent.com/44613082/199794402-f0bf9ed5-dc11-4e14-9906-7bddfd22ab30.png">

### Versions
- Plugin version: 4.0.2
- Craft version: Craft Pro 4.3.1

**Comment by khalwat** [comment]
So I don't think this is a bug with ImageOptimize. All it is doing is providing the available images that the browser can use; which it uses is up to the browser.

Ensure that you're checking which image is actually being used by clicking on the image, and then inspecting the `currentSrc` property. More here: https://stackoverflow.com/questions/30900173/is-it-possible-to-see-which-srcset-image-a-browser-is-using-with-browser-develop

It's also possible that the issue here is you're not using `sizes` to specify at which size each image should be used (I don't think `auto` is a valid value for this property). There's a good tutorial on that here:

https://ericportis.com/posts/2014/srcset-sizes/
