### ISSUE TITLE
Make use of an alias for transformed image URL's / variants

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-imageoptimize#372]
We needed to change the domain name of our content server on which we are hosting all assets like images, so I changed some aliases in Craft that we are using for different fields like thumbnails, but then I noticed that all variant images that are generated by ImageOptimize, have a static URL in the database, referring to the old / full URL. 

Two questions;

1) why is this? 
2) why isn't an alias used for this?

If I am correct, there's only one way to fix this: changing the alias in Craft and re-generate all variants? As we have 150k+ image assets this is really time consuming proces, risking timeouts, etc. Have tried it before.

For now I wrote an Twig extension that that replaces the domain of an image URL with the alias domain from Craft in all my templates where we're showing image variants, but it's not ideal.

Or am I missing something?

**Comment by khalwat** [comment]
That's correct -- the reason is that it saves an actual, usable URL when it generates the images.

Potentially an alias could be used, which would help in cases like yours, but it would require retooling how things work a bit, because you don't want to then end up with a URL like `@assets/images/image.png` in your templates.

There is another issue open regarding this already:

https://github.com/nystudio107/craft-imageoptimize/issues/78
