### ISSUE TITLE
Queue image variants

### ISSUE THREAD

**Issue by riasvdv** [nystudio107/craft3-imageoptimize#38]
Is it possible to queue all generation of image variants? 

Uploading/saving an image now takes a long time for the user while they won't instantly need to view the variants anyway.

**Comment by khalwat** [comment]
I'm slightly torn on this, because I want to create the variants on Asset save... and a natural thing that people do right after uploading an image is they double-click on it to have a look at it.

**Comment by riasvdv** [comment]
Maybe something like a placeholder image that says "Image being generated" could work?

They'd have to wait anyway for the processing, either on asset save or after to view them immediately, but for people that want to just upload and continue doing something else, it would be a lot quicker

**Comment by davidhellmann** [comment]
Don't know how this Plugins work in detail but I've used it a lot in the WordPress world and when I remember right it works nicely in the background. That was nice :)

**Comment by khalwat** [comment]
I implemented this, the problem is that if you invoke the image editor from an Asset HUD, it refreshes the display immediately... and the image variants don't appear, as they are being created in the background.

I've spent some time looking into a way to get the display to refresh after the images are generated, but I haven't found a way to hook in to do that yet.

**Comment by khalwat** [comment]
Okay so in version 1.4.15 (just released), if it's a newly created Asset (someone uploads it), it creates all of the variants via a background queue.

If it's an existing Asset, it creates the variants immediately, because they may have the AssetSelector HUD open, and we want to display the correct images when it refreshes:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.15

It's a half-solution, until I can figure out a way to refresh the AssetSelectorHud or load the images via controller or such.

**Comment by riasvdv** [comment]
Seems like a great half-solution 😄 I think this covers most use-cases though, I'd expect it to take longer when editing the image anyway, but just uploading should be fast, which it is now. Great work 👍
