### ISSUE TITLE
Moving images to a folder makes the site unresponsive

### ISSUE THREAD

**Issue by riasvdv** [nystudio107/craft3-imageoptimize#55]
When ImageOptimize is enabled and you try to move some images to a subfolder, it optimizes all the images again, which it shouldn't do as the images themselves have not been changed. 

When you try to move a lot of them at once, everything just hangs and makes the site unresponsive.

**Comment by khalwat** [comment]
So I think the reason this happens is that under the hood, Craft probably does something like deleting the assets from one Asset Volume, and moving them to the other. Given that asset transforms sit in a folder in the same sub-folder as the asset, all of the transforms and their parents folders would need to be moved when an Asset is moved.

The real "bug" here I think would be for P&T, where we might want it to (maybe?) move any generated transforms when an Asset is moved, rather than just expecting them to be recreated (which is what it sounds like is happening).

This is without looking into it in depth, just what I think is likely happening.

**Comment by riasvdv** [comment]
Yeah I haven't looked into what was really happening either, though I don't think P&T are recreating the assets as the IDs are kept exactly the same, only a `folderPath` column gets changed in the database. But maybe the events that are being triggered are the same as deleting/adding

**Comment by khalwat** [comment]
What's happening is that when you move a bunch of images, the transforms all get nuked, and then ImageOptimize goes to recreate them... but it does it immediately, so it can take some time to do if there are a bunch of them.

I'll see if there is a way to shuffle it off into a queue in this instance.

**Comment by khalwat** [comment]
This should be addressed in 1.4.23:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.23

**Comment by riasvdv** [comment]
Great, that fixed it!
